### ISSUE TITLE
Unable to resolve plugin cdk-multi-profile-plugin

### ISSUE THREAD

**Issue by asterikx** [hupe1980/cdk-multi-profile-plugin#6]
When running `cdk synth` I get the error:

```
Unable to resolve plugin cdk-multi-profile-plugin: Error: Cannot find module 'cdk-multi-profile-plugin'
Require stack:
- /Users/username/.nvm/versions/node/v12.16.1/lib/node_modules/aws-cdk/bin/cdk.js
- /Users/username/.nvm/versions/node/v12.16.1/lib/node_modules/aws-cdk/bin/cdk
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.resolve (internal/modules/cjs/helpers.js:83:19)
    at tryResolve (/Users/username/.nvm/versions/node/v12.16.1/lib/node_modules/aws-cdk/bin/cdk.ts:150:24)
    at loadPlugins (/Users/username/.nvm/versions/node/v12.16.1/lib/node_modules/aws-cdk/bin/cdk.ts:140:26)
    at initCommandLine (/Users/username/.nvm/versions/node/v12.16.1/lib/node_modules/aws-cdk/bin/cdk.ts:158:3)
Unable to resolve plug-in: cdk-multi-profile-plugin
```

I followed the [documentation of this plugin](https://github.com/hupe1980/cdk-multi-profile-plugin/blob/master/cdk-multi-profile-plugin/README.md).

I'm using version `1.27` of `aws-cdk`. Not sure if the error is related to this plugin or `aws-cdk`.

**Comment by hupe1980** [comment]
It appears that you are using the global cdk. Try the local version:
```
//package.json
"scripts": {
        "cdk": "cdk"
},
npm run cdk ...
```

**Comment by asterikx** [comment]
True. Using `yarn run cdk` solved the issue. Thanks a lot!
