### ISSUE TITLE
Fail to upload asset with CDK v1.29.0 and v1.30.0

### ISSUE THREAD

**Issue by matsev** [hupe1980/cdk-multi-profile-plugin#9]
After updating the AWS CDK to version 1.30.0 (or 1.29.0), it is no longer possible to deploy stacks with assets if the AWS CLI profile has been configured with MFA authentication.

Consider the following files:

_bin/test.ts_
```typescript
#!/usr/bin/env node
import * as cdk from '@aws-cdk/core';
import { LambdaIntegration, RestApi } from '@aws-cdk/aws-apigateway';
import { Function, InlineCode, Runtime } from '@aws-cdk/aws-lambda';
import { RetentionDays } from '@aws-cdk/aws-logs';

class TestStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const lambda = new Function(this, 'Lambda', {
      runtime: Runtime.NODEJS_12_X,
      code: new InlineCode('exports.handler = function(event, ctx, cb) { return cb(null, "hi"); }'),
      handler: 'index.handler',
      logRetention: RetentionDays.ONE_DAY,
    });

    const restApi = new RestApi(this, 'RestApi');
    restApi.root.addMethod('GET', new LambdaIntegration(lambda), {
    });
  }
}

const app = new cdk.App();
new TestStack(app, 'TestStack', {
  env: {
    account: '111222333444',
    region: 'eu-west-1',
  },
});
```
_cdk.json_
```json
{
  "app": "npx ts-node bin/test.ts",
  "plugin": ["cdk-multi-profile-plugin"]
}
```
_cdkmultiprofileplugin.json_
```json
{
  "awsProfiles": {
    "111222333444": "mfa-profile"
  }
}
```
_package.json_
```json
{
  "name": "test",
  "version": "0.1.0",
  "bin": {
    "test": "bin/test.js"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "test": "jest",
    "cdk": "cdk"
  },
  "devDependencies": {
    "@aws-cdk/aws-apigateway": "^1.30.0",
    "@aws-cdk/aws-lambda": "^1.30.0",
    "@aws-cdk/core": "1.30.0",
    "@types/jest": "^24.0.22",
    "@types/node": "10.17.5",
    "aws-cdk": "1.30.0",
    "cdk-multi-profile-plugin": "^1.1.2",
    "jest": "^24.9.0",
    "ts-jest": "^24.1.0",
    "ts-node": "^8.1.0",
    "typescript": "~3.7.2"
  }
}
```

Using CDK version 1.28.0 (or lower) it was possible to deploy this stack. However, after the upgrade it fails:

```bash
$  npm run build && npx cdk deploy
> test@0.1.0 build /Users/mattias/Projects/Bombardier/test
> tsc

 🚀  Using profile mfa-profile for account 111222333444 in mode ForReading

? MFA token for arn:aws:iam::111222333444:mfa/some-user: 492769
Do you wish to deploy these changes (y/n)? y
TestStack: deploying...

 🚀  Using profile mfa-profile for account 111222333444 in mode ForWriting
[0%] start: Publishing [random string]:current
[100%] fail: AWS credentials are required to upload assets. Please configure environment variables or ~/.aws/credentials.

 ❌  TestStack failed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at Object.publishAssets (/Users/test/node_modules/aws-cdk/lib/util/asset-publishing.ts:18:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.deployStack (/Users/test/node_modules/aws-cdk/lib/api/deploy-stack.ts:132:3)
    at CdkToolkit.deploy (/Users/test/node_modules/aws-cdk/lib/cdk-toolkit.ts:152:24)
    at main (/Users/test/node_modules/aws-cdk/bin/cdk.ts:229:16)
    at initCommandLine (/Users/test/node_modules/aws-cdk/bin/cdk.ts:172:9)
Failed to publish one or more assets. See the error messages above for more information.
```

**Comment by hupe1980** [comment]
Is the problem still existent?

**Comment by matsev** [comment]
No, after modifying the dependencies and node runtime (see below) I was successfully able to deploy the stack.

- aws-cdk: 1.38.0
- cdk-multi-profile-plugin: 1.1.3
- aws-sdk: 2.673.0
- node: v12.14.1
